project:
  type: book

book:
  title: "Latex Starter Guide"
  author: "Dominic Skinnion"
  date: "last-modified"
  page-navigation: true
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - comparison.qmd
        - overleaf.qmd
        - vscode.qmd
        - emacs.qmd
    - part: "Suggested Tools"
      chapters:
        - github.qmd
        - copilot.qmd
    - part: "Documents"
      chapters:
        - articles.qmd
        - presentations.qmd
    - part: "Resources"
      chapters:
        - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple

execute:
  freeze: auto

